const fs = require('fs'), vm = require('vm');
const ctx = vm.createContext({ console, URL, localStorage: {}, document: {}, state: {} });
vm.runInContext('function extractDomain(u){return u;}', ctx);
vm.runInContext(fs.readFileSync('helpers.js', 'utf8'), ctx);
const run = (s) => vm.runInContext(s, ctx);
let fail = 0;
const t = (expr, exp) => { const r = run(expr); const ok = Object.is(r, exp) || (typeof exp === 'number' && typeof r === 'number' && Math.abs(r - exp) < 1e-9); if (!ok) { fail++; console.log('FAIL', expr, '=>', r, 'expected', exp); } };
const E = (s) => `MathSolver.evaluate(${JSON.stringify(s)})`;
t(E('2+3*4'), 14); t(E('(2+3)*4'), 20); t(E('2^3^2'), 512); t(E('-2^2'), -4); t(E('2^-1'), 0.5);
t(E('sqrt(16)+pow(2,3)'), 12); t(E('2 ** 10'), 1024); t(E('sin(pi/2)'), 1); t(E('log2(8)'), 3);
t(E('1/0'), null); t(E('2+'), null); t(E('constructor'), null); t(E('toString(1)'), null); t(E('__proto__'), null);
t(E('alert(1)'), null); t(E('sqrt(1,2)'), null); t(E('('.repeat(40) + '1' + ')'.repeat(40)), null);
t(E('1'.repeat(300)), null); t(E('2;3'), null); t(E('2 3'), null); t(E('9^9^9^9'), null);
t(`safeUrl('javascript:alert(1)')`, null); t(`safeUrl('data:text/html,x')`, null); t(`safeUrl('/rel')`, null);
t(`safeUrl('https://a.b/x')`, 'https://a.b/x'); t(`safeUrl('http://a.b', true)`, null);
t(`validateEndpoint('https://api.example.com/')`, 'https://api.example.com'); t(`validateEndpoint('http://x.com')`, null);
t(`validateEndpoint('https://user:p@x.com')`, null); t(`validateEndpoint('https://127.0.0.1')`, null);
t(`validateEndpoint('https://192.168.1.5')`, null); t(`validateEndpoint('https://localhost')`, null);
t(`validateEndpoint('https://[::1]')`, null); t(`validateEndpoint('https://x.com/?a=1')`, null); t(`validateEndpoint('')`, '');
t(`validateEndpoint('https://0x7f.1')`, null); t(`validateEndpoint('https://8.8.8.8/api')`, 'https://8.8.8.8/api');
t(`normalizeQuery('  a\\u0000b \\n c ')`, 'a b c'); t(`normalizeQuery('x'.repeat(999)).length`, 256);
t(`normalizeItem({url:'javascript:1',title:'t'},'s','neoncyan')`, null);
t(`normalizeItem({url:'https://a.b',title:'t',favicon:'http://x/y.png'},'s','c').favicon`, null);
t(`normalizeItem({url:'https://a.b',title:'t'},'s','evil"x').color`, 'neoncyan');
console.log(fail ? 'FAILED ' + fail : 'ALL OK');
