# Exported from Render on 2026-07-11T06:33:26Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: anonymousik.github.io
      runtime: node
      repo: https://github.com/anonymousik/anonymousik.github.io
      plan: free
      envVars:
      - key: ALLOWED_ORIGIN
        sync: false
      region: frankfurt
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
      rootDir: scripts/webterm/backend
